/*
 * Copyright Grafana Labs
 * SPDX-License-Identifier: Apache-2.0
 */

package com.grafana.opentelemetry;

// This class is generated by custom/build.gradle.  Do not edit.

public class DistributionVersion {

  public static final String VERSION = "1.4.0";
}
